### ISSUE TITLE
kubectl credentials

### ISSUE THREAD

**Issue by oonid** [waprin/kubernetes_django_postgres_redis#6]
dear @waprin thanks for the great article.
I tried following the 1st part.

until this step:
```
# Configure kubectl with the right context
gcloud container clusters get-credentials guestbook
```

would you please add some information about this lines?
so beginner user like me still understand the flow.
(I didn't understand what is "the right context"?)

then I continue to the next lines,
about the kubectl.
when I tried, I got error:
```
error: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
```
I have checked the kubectl config view. the clusters and the contexts have been set, but the users was not.

I got this command that solved my problem: 
```
gcloud auth application-default login
```
should we add it to the article?

thank you for your response.

**Comment by waprin** [comment]
@oonid Thanks for the feedback. Yes I agree that I should add that authentication command. I will add it in the next edit.

Can you give me suggestion on how to improve the information about the context?

The context means which Kubernetes cluster the  `kubectl` tool is  talking to. So when you want to talk to a Container Engine cluster, or you local Minikube cluster, you switch to that context. 

Would it maybe be more clear if the comment just said "Configure kubectl to talk to Container Engine"?

**Comment by oonid** [comment]
@waprin this information should be clear enough.

"The context means which Kubernetes cluster the kubectl tool is talking to. So when you want to talk to a Container Engine cluster, or you local Minikube cluster, you switch to that context."

but, following the 1st part of your article now is getting harder to understand because it's not synchronized with the source code anymore. (for example about frontend.yaml)
The source code become more complex, because of the Minikube compatibility.
after reading all of those 3 articles, also check the previous code from previous commits, finally I understand about the objective of the 1st part of the article.
So I think the 1st article need to be re-structured.

And hopefully, it still support the very beginner reader of kubernetes (like me). either it is more detail step by step to work with the source code. or maybe a new branch that work simply with kubernetes on GCP.

once again, thank you for the articles.

**Comment by waprin** [comment]
@oonid fair point, The project has evolved which has made the old tutorials out of date as you note. I guess the simplest thing to do is take the project's commits from a few months ago and move that into a separate branch. 

The simplest Django on Kubernetes tutorial is the one we have [here](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/container_engine/django_tutorial) , which is even simpler because you just run Django, and use CloudSQL instead of running Postgres in Kubernetes yourself.

Ok, I will take another pass at your suggestion before I close this issue ,thanks for feedback.

**Comment by waprin** [comment]
Added link to branch with code associated with part 1/part2, added gcloud adc command, thanks again for feedback!!
