### ISSUE TITLE
How does Django get the Postgres password?

### ISSUE THREAD

**Issue by tswast** [waprin/kubernetes_django_postgres_redis#7]
Some context: I'm trying to run [Weblate](https://weblate.org/en/) on Kubernetes, with the eventual goal of creating a Helm chart.

From what I can understand, Weblate and other Django apps use a `settings.py` (module name configurable for some reason) module to store database passwords and other config-y stuff. At least it [looks like I have to put it in there](https://docs.weblate.org/en/latest/admin/install.html#database-setup). Maybe Django settings can be overridden with environment variables? Forgive me for my ignorance.

My searching for "django kubernetes settings.py" brought me here (and also here: https://github.com/hnarayanan/kubernetes-django) but as far as I can tell the latter builds `settings.py` into the Docker container and you parse a YAML file with the secrets in it. Maybe there isn't a general way to do it, and I need to modify Weblate to be able to read a config file rather than try to shoe-horn a Python module in with Secrets?

**Comment by waprin** [comment]
@tswast sorry for delay here.

My settings.py reads it from the secrets file. That could be changed to environment variables which I think Kubernetes now supports (previously secrets could only be files).

I think either building it into the container or reading from the secret is ok, the advantage of the secrets is your images don't have to be secret (easier to manage) and they can be reused in different contexts. So I think building it into the image is slightly worse though probably ok in many cases. 

As far as overriding the Django settings, I don't think that could be done with environment variables so you have to use code anyway. Might as well just change the settings.py file to read the config file imo.
